### ISSUE TITLE
keymaps for `gg` and `G`

### ISSUE THREAD

**Issue by mosheavni** [niuiic/scroll.nvim#1]
Hi, nice plugin!
can you please add an example of `gg` and `G` mappings?
Thanks.

**Comment by niuiic** [comment]
```lua
		function()
			local screen_h = vim.opt.lines:get() - vim.opt.cmdheight:get()
			local target_line = vim.api.nvim_win_get_cursor(0)[1] + screen_h / 2
			local step = screen_h / 2 / 50
			if step < 1 then
				step = 1
			end

			require("scroll").scroll(target_line, function(current_line)
				return {
					next_line = current_line + step,
					-- 10ms
					delay = 10,
				}
			end)
		end,
```

Code above is the example for `<C-d>`. You just need to specify three arguments.

1. target_line: where you want to go
2. next_line: where you are for next step
3. delay: time waiting for next step

For `gg`, just modify `target_line` to 0, and `next_line` should be smaller than the `current_line`, maybe you can use `next_line = current_line - step`.

**Comment by niuiic** [comment]
`next_line` and `delay` could be used to control your smooth strategy.

In the example for `<C-d>`, it is split into 50 small steps, and each step has the same distance. The cursor moves at a constant speed.

**Comment by niuiic** [comment]
For `G`, you can use `vim.api.nvim_buf_line_count(0)` to get buffer line cout.
